# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Test_LaFourchette' do
pod 'Alamofire', '~> 3.4'               #Swift - Used to handle network communication layer
pod 'AlamofireObjectMapper', '~> 3.0'   #Swift - Used to handle network datas and binding directly into a full BO

end

target 'Test_LaFourchetteTests' do

end

target 'Test_LaFourchetteUITests' do

end

